### ISSUE TITLE
לכבוד יקיר

### ISSUE THREAD

**Issue by itamargs** [itamargs/Milestones#2]
@yakir2a 
לרשום קוד התנהגות לצוות
מה דרושים מעצמנו
מה אנו מקבלים על עצמנו
דרכי התקשרות מתוכננות אל/בין הצוות
puts everything inside the "Team " link in the readme.md file

"לרשום הכל אחרי ה"זיהוי לקוח

**Comment by yakir2a** [comment]
Done!
