### ISSUE TITLE
Check project3-srs-submission

### ISSUE THREAD

**Issue by aviel-sh** [itamargs/Milestones#4]
@kob-e 

[link](https://github.com/itamargs/Milestones/wiki/srs)

**Comment by robi-y** [comment]
You also need to assign @kob-e on the left -->

**Comment by robi-y** [comment]
- assign lecturer
- use external login?
- stakeholder: AMUTA and others
- uc diagram: box around use cases, user inheritance, 
- UC1: focus main scenario
- details 2nd use case
- Update initial screens

**Comment by aviel-sh** [comment]
@robi-y 

[wiki srs](https://github.com/itamargs/Milestones/wiki/srs)

**Comment by robi-y** [comment]
I don't see much changes. Anyway let's continue to the next phase
