### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [itamargs/Milestones#5]
- Team page: no diversity
- README file: broken link (user manual)
- Inception: There are no risks associated with the project itself

**Comment by YaakovHatam** [comment]
@amosdabu @yakir2a @itamargs @IdoZaken @aviel-sh 
תייגו אותי כשאתם מסיימים עם השינויים

**Comment by aviel-sh** [comment]
היי קובי, סיימנו עם השינויים.
שבוע טוב.
@kob-e
